### ISSUE TITLE
CSS to enlarge minimap on hover

### ISSUE THREAD

**Issue by N3C2L** [ifree/Obsidian-canvas-minimap#10]
I am not a coder, just know a little CSS here and there and would need your help, please.

I want to create a CSS snippet; having a small canvas minimap which enlarges on hover.

I tried the following CSS but without success:

```
div#_minimap_ {
    min-width: 50px !important;
    min-height: 50px !important;
     width: 50px !important;
    height: 50px !important;
}

div#_minimap_ .svg {
    min-width: 50px !important;
    min-height: 50px !important;
     width: 50px !important;
    height: 50px !important;
}

div#_minimap_:hover {
        min-width: 200px !important;
    min-height: 150px !important;
      width: 200px !important;
    height: 150px !important;
}

div#_minimap_ .svg:hover {
        min-width: 200px !important;
    min-height: 150px !important;
      width: 200px !important;
    height: 150px !important;
}

```
Can you help me here? Maybe I need a new class?

**Comment by ifree** [comment]
Hi, I don't know too much about the css either as a non-web guy, but I'll try to help you out in the next few weekends(don't have much time during the weekdays).

**Comment by N3C2L** [comment]
Alright, thank you.

**Comment by N3C2L** [comment]
It's not that important, but feel free to implement it with javascript/typescript if you want.
