### ISSUE TITLE
Zoom level

### ISSUE THREAD

**Issue by N3C2L** [ifree/Obsidian-canvas-minimap#4]
Hello and thank you for this plugin!

I would be happy if you could implement a new setting: "Keep zoom level when clicking in the minimap" or "Don't zoom the canvas when clicking in the minimap". That would be great! What do you think?

**Comment by ifree** [comment]
Sure thing, already working on similar feature, will be available in next few releases.

**Comment by N3C2L** [comment]
Thanks! Looking forward to the next releases.

**Comment by N3C2L** [comment]
Thank you for the new possibility to disable the zoom while holding the control key.
But may I ask you if you could introduce a new setting (maybe a checkbox in the settings menu) > To disable zooming while clicking left click, and enable zooming while clicking with the control key. So that the behavior of this current method could be reversed in the settings page of the canvas minimap plugin.
That would really help me.

**Comment by ifree** [comment]
@N3C2L 6ed1574 should address your concern, feel free to reopen the issue if you have any further questions

**Comment by N3C2L** [comment]
This is awesome, thanks. 
Just tested it and it works wonderfully.
Just a little enhancement I have in my mind regarding this feature request. An addition to the navigation strategy for a double left click for either panning or zooming. That would be really great.
