### ISSUE TITLE
Canvas minimap unable to focus on specific area when embedded document is zoomed in to a title or block.

### ISSUE THREAD

**Issue by PandaNocturne** [ifree/Obsidian-canvas-minimap#5]
Unable to focus on specific area when left-clicking on canvas minimap while embedded document inside Canvas is zoomed in to a title or block.

If the embedded document inside my Canvas is zoomed in to a title or block, then left-clicking on the canvas minimap will not focus on that area.

**Comment by ifree** [comment]
The zooming in feature is offered by native Obsidian canvas, can you reproduce it by right-clicking a canvas block and selecting "Zoom to selection"?

**Comment by PandaNocturne** [comment]
Upon retesting, I found that it is indeed possible to jump to a block reference. The issue I encountered before was due to a problem with the canvas document I was testing. I apologize for any disturbance caused to your time.
